services:
  - type: web
    name: saral-bhoomi-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: your-mongodb-connection-string
      - key: JWT_SECRET
        value: your-jwt-secret-key
      - key: CORS_ORIGIN
        value: https://your-vercel-app.vercel.app