services:
  # Frontend Service
  - type: web
    name: saral-bhoomi-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    branch: features/working-fine
    autoDeploy: true
    envVars:
      - key: VITE_FORCE_DEMO_ANALYTICS
        value: "0"
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /api/*
        destination: https://saral-bhoomi-1.onrender.com/api/:splat
      - type: rewrite
        source: /uploads/*
        destination: https://saral-bhoomi-1.onrender.com/uploads/:splat
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend Service
  - type: web
    name: saral-bhoomi-backend
    env: node
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    branch: features/working-fine
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      # Render will inject PORT automatically; no need to hardcode
      - key: CORS_ORIGIN
        value: https://saral-bhoomi-frontend.onrender.com,https://saral-bhoomi-2.onrender.com
      # MongoDB Atlas connection string (set value in Render dashboard)
      - key: MONGODB_URI
        sync: false
      - key: DATABASE_URL
        value: postgres://user:password@host:5432/dbname?sslmode=require
      - key: JWT_SECRET
        value: change-me
      # Cloudinary (optional but recommended for files)
      - key: CLOUDINARY_CLOUD_NAME
        value: dmytltj0w
      - key: CLOUDINARY_API_KEY
        value: 269548842743513
      - key: CLOUDINARY_API_SECRET
        sync: false
      # Firebase (optional)
      - key: FIREBASE_SERVICE_ACCOUNT_B64
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        value: ''