services:
  - type: web
    name: saral-bhoomi-backend
    env: node
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      # MongoDB Atlas connection - UPDATE WITH YOUR ACTUAL CONNECTION STRING
      - key: MONGODB_URI
        value: mongodb+srv://username:password@cluster.mongodb.net/saral_bhoomi?retryWrites=true&w=majority
      # JWT Secret - UPDATE WITH YOUR SECURE SECRET
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-minimum-32-characters-long-random-string
      # Frontend CORS origin - UPDATE WITH YOUR VERCEL URL
      - key: CORS_ORIGIN
        value: https://your-app.vercel.app
      # Cloudinary Configuration - UPDATE WITH YOUR VALUES
      - key: CLOUDINARY_CLOUD_NAME
        value: your_cloud_name
      - key: CLOUDINARY_API_KEY
        value: your_api_key
      - key: CLOUDINARY_API_SECRET
        sync: false
      # Optional: Firebase Configuration
      - key: FIREBASE_PROJECT_ID
        value: your-project-id
      - key: FIREBASE_SERVICE_ACCOUNT_B64
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        value: your-project-id.appspot.com